// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe-ebAPttEW95fgDbnWcu7VsdrZqgQNuo',
    appId: '1:807389330916:web:ab8718e5c305f71bdd5bf1',
    messagingSenderId: '807389330916',
    projectId: 'e-commerce-a762f',
    authDomain: 'e-commerce-a762f.firebaseapp.com',
    storageBucket: 'e-commerce-a762f.appspot.com',
    measurementId: 'G-08XKXB9TX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB17XYf7bhcSnZd6RFYySl2jv1M9ZcM3sI',
    appId: '1:807389330916:android:0a47f14094debeb5dd5bf1',
    messagingSenderId: '807389330916',
    projectId: 'e-commerce-a762f',
    storageBucket: 'e-commerce-a762f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY3oid3GiCJW_rwz_Tr_ev4aFTRvX0PRc',
    appId: '1:807389330916:ios:ff1d357d524fe4c9dd5bf1',
    messagingSenderId: '807389330916',
    projectId: 'e-commerce-a762f',
    storageBucket: 'e-commerce-a762f.appspot.com',
    iosClientId: '807389330916-235strrisasbhmo2eeucnvacongt0lbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
